---
- hosts: win
#  become: yes
#  become_user: Administrator
  gather_facts: no

  tasks:
  - name: Install only particular updates based on the KB numbers
    win_updates:
      category_name:
      - SecurityUpdates
      whitelist:
      - KB5005076
      reboot: yes
    register: patch_status

  - debug:
      var: patch_status
